#base image
FROM node:20.3.1

# set working directory
RUN mkdir /usr/src/app

#copy all files from current directory to docker
COPY ./manualbuild /usr/src/app/dist

# add `/usr/src/app/node_modules/.bin` to $PATH
#ENV NODE_OPTIONS="--openssl-legacy-provider --max_old_space_size=8192"
#ENV PATH /usr/src/app/node_modules/.bin:$PATH
ENV CURRENT_ENVI=prod

# Build mfe-container
WORKDIR /usr/src/app
RUN npm i -g serve

#RUN npm config rm proxy
EXPOSE 3000

# start app
#CMD ["npm", "start"]
CMD ["serve", "-s", "dist"]
#CMD ["node", "server.js"]

# production environment =====
#FROM nginx:stable-alpine
#COPY --from=base /usr/src/app/build /usr/share/nginx/html/marinem
#COPY ./default.conf /etc/nginx/conf.d/default.conf

# In ECS no need to define HEALTHCHECK in docker
#HEALTHCHECK CMD curl --fail http://localhost/marinem || exit 1
#EXPOSE 3000
#CMD ["nginx", "-g", "daemon off;"]